# Generated by Django 5.0.3 on 2024-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('empdesignation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
    ]
